### ISSUE TITLE
Mass Mute functionality is not working

### ISSUE THREAD

**Issue by ddelboccio** [jay0lee/Meet-Extensions#5]
Good morning.  The Mass Mute feature is not working, only the Mass Kick appears to be working.  clicking Mass Mute does nothing to all the participants, but clicking Mass Kick DOES kick everyone out.  Is there an update available to this extension possibly?  THANKS!

**Comment by ddelboccio** [comment]
Follow-up, "Mass Mute" feature is working sporadically.  Some users can use it just fine, others the button simply does nothing.  However, "Mass Kick" always works for everyone.  Possible issue with version of Chrome browser?  Mine is 80.0.3987.163 on a Windows 10 PC.

**Comment by ddelboccio** [comment]
My Windows Chrome browser just updated to Version 81.0.4044.92, and "Mass Mute" feature appears to be working again.  Maybe it was a version related issue??

**Comment by ddelboccio** [comment]
And to follow up, it still is only working intermittently.  Cannot figure out why "Mute Everyone" only works about 50% of the time, while "Kick Everyone" works 100% of the time.

**Comment by stallionh1** [comment]
This is an important extension. We teachers have been looking for this. There is a "Meet Enhancement Suite," but they put this feature in the paid version.

However, I have the same issue. In my case, "Mute Everyone" never worked, but "Kick Everyone" always worked. Any workaround on this concern? Thank you.

I am using Windows 8.1.

**Comment by stallionh1** [comment]
I tried my other laptop, which is running on Windows 10. "Mute Everyone" worked at first, I tried a few number of times, it really worked. But after shifting from one account to another in Meet, it started not working again. 

Does anyone know how to solve the problem? Thank you.

**Comment by jay0lee** [comment]
OK, I've made a few changes and updated the extension to version 1.07 which should hopefully maybe / possibly fix the mute issue.

Full disclaimer here, I offer no guarantee of support for this extension. It may not work now and it may cease working in the future. My life is pretty busy these days so I cannot promise if or when I'll be able to fix issues. Good luck and hope this fix works for you.

Jay
